version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-prod
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend-prod
    depends_on:
      - sqlserver
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-prod:1433;databaseName=assurance;encrypt=false;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=${MSSQL_SA_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
    ports:
      - "${APP_PORT}:9099"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend-prod
    depends_on:
      - backend
    ports:
      - "${WEB_PORT}:80"

volumes:
  sqlserver_data:
