version: "3.9"
name: assurance-infra

services:
  db:
    image: mysql:8.0
    container_name: mysql-assurance
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assurance
    ports:
      - "3306:3306"   # si déjà pris, remplace par "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15

  backend:
    image: assurance-backend:latest
    build:
      context: ./backend-assurance
      dockerfile: Dockerfile
    container_name: backend-assurance
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/assurance?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9099:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: assurance-frontend:latest
    build:
      context: ./frontend-assurance
      dockerfile: Dockerfile
    container_name: frontend-assurance
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
