services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: assurance-keycloak
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=dev-file
    command: start-dev
    # Sonde "toujours OK" pour CI (évite le blocage service_healthy)
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
    networks: [assurance-network]
    volumes:
      - keycloak-data:/opt/keycloak/data

  backend:
    build:
      context: ./backend-assurance
      dockerfile: Dockerfile
    image: mariemftouhi/assurance-backend:${IMAGE_TAG:-latest}
    container_name: assurance-backend
    restart: unless-stopped
    ports:
      - "9099:9099"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - KEYCLOAK_URL=http://keycloak:8080
    depends_on:
      keycloak:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9099/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks: [assurance-network]

  frontend:
    build:
      context: ./frontend-assurance
    image: mariemftouhi/assurance-frontend:${IMAGE_TAG:-latest}
    container_name: assurance-frontend
    restart: unless-stopped
    # Image finale = NGINX → écoute 80
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ | grep -qi '<html'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks: [assurance-network]

  ml-fraud-service:
    build:
      context: ./ml-fraud-service
    image: mariemftouhi/ml-fraud-service:${IMAGE_TAG:-latest}
    container_name: ml-fraud-service
    restart: unless-stopped
    # Évite les conflits en CI : port hôte aléatoire
    ports: ["5000"]
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5000/health | grep -q OK"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks: [assurance-network]

  ml-fraud-service-2:
    build:
      context: ./ml-fraud-service-2
    image: mariemftouhi/ml-fraud-service-2:${IMAGE_TAG:-latest}
    container_name: ml-fraud-service-2
    restart: unless-stopped
    ports: ["5001"]   # port hôte aléatoire
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5001/health | grep -q OK"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks: [assurance-network]

networks:
  assurance-network:
    driver: bridge

volumes:
  keycloak-data:
    driver: local
