services:
  keycloak:
    ports: ["127.0.0.1::8080"]

  backend:
    ports: ["127.0.0.1::9099"]

  frontend:
    ports: ["127.0.0.1::80"]

  ml-fraud-service:
    ports: ["127.0.0.1::5000"]
    # supprime tout mount hérité :
    volumes: null

  ml-fraud-service-2:
    ports: ["127.0.0.1::5001"]
    # supprime tout mount hérité :
    volumes: null
  metabase:
    ports: ["127.0.0.1::3000"]

