version: '3.8'

services:
  # Service pour le Backend (Votre application Java)
  backend:
    image: assurance-backend:latest
    container_name: backend-service-devops
    ports:
      - "9099:9099"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/assurance?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - KEYCLOAK_REALM=assurance
      - KEYCLOAK_AUTH_SERVER_URL=http://host.docker.internal:9090
    restart: unless-stopped

  # Service pour le Frontend (Votre application Angular)
  frontend:
    image: assurance-frontend:latest
    container_name: frontend-service-devops
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped